# The number of seconds to wait for a proxied request.
# The higher the number, the longer the check will take
# and the more proxies you get.
timeout = 5

# The number of seconds to wait for the proxies to be downloaded from the source.
source_timeout = 15

# Maximum concurrent connections.
# Windows supports maximum of 512.
# On *nix operating systems, this restriction is much looser.
# The limit on *nix can be seen with the command `ulimit -Hn`.
# Don't be in a hurry to set high values.
# Make sure you have enough RAM first, gradually increasing the default value.
# If set to 0, the maximum value available for your OS will be used.
max_connections = 512

# URL to which to send a request to check the proxy.
# If it is not httpbin or a service that returns an IP address,
# it will be impossible to determine the anonymity and geolocation of the proxy.
# Example:
# check_website = "https://google.com"
# check_website = "https://checkip.amazonaws.com"
check_website = "https://httpbin.smp.io/ip"

# Set to false to sort proxies alphabetically.
sort_by_speed = true

# Save the geolocation of the proxy exit-node.
# Uses offline geolocation database.
# Only works for json output.
enable_geolocation = false

# Enable output of all errors. Significantly slows down proxy checking.
debug = false

[output]
# Path to the folder where the proxies will be saved.
# Leave blank to save the proxies to the current directory.
# This option is ignored in Docker.
path = "./out"

json = false
txt = true

# If you have sources with a protocol prefix, such as socks5://127.0.0.1:1050, you can add them to any of these sections.
[http]
enabled = true
sources = [
    # Local proxy list example
    # "./http_proxies.txt",
    "https://api.openproxylist.xyz/http.txt",
]

[socks4]
enabled = true
sources = [
    # Local proxy list example
    # "./socks4_proxies.txt",
    "https://api.openproxylist.xyz/socks4.txt",
]

[socks5]
enabled = true
sources = [
    # Local proxy list example
    # "./socks5_proxies.txt",
    "https://api.openproxylist.xyz/socks5.txt",
]
