name: scrapper
on:
  schedule:
    - cron: '30,00 * * * *'

jobs:
  scrap:
    name: scrap that proxies
    runs-on: ubuntu-latest
    steps:
        - name: Setup Python
          uses: actions/setup-python@v5.1.0
          with:
            python-version: 3.11
        - name: install libs
          run:
            pip install -r requirements.txt
        - name: Execute the scrapper
          run:
            python3 main.py
