name: scrapper
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: 

jobs:
  scrap:
    name: scrap that proxies
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v5.1.0
          with:
            python-version: 3.11
            cache: "pip"
        - run: pip install --disable-pip-version-check --editable .[non-termux]
          
        - name: run a start.sh
          
          run: |
            chmod +x start.sh
            ./start.sh
            
        - name: push to repo
          uses: ad-m/github-push-action@v0.6.0
          with:
            github_token:  ${{ secrets.GITHUB_TOKEN }}
            directory: .
          
