name: scrapper
on:
  schedule:
    - cron: '30,00 * * * *'
  workflow_dispatch: 

jobs:
  scrap:
    name: scrap that proxies
    runs-on: ubuntu-latest
    steps:
        - name: Setup Python
          uses: actions/setup-python@v5.1.0
          with:
            python-version: 3.11
        - name: Execute the scrapper
          run: 
            ls
            chmod +777 start.sh
            ./start.sh
